//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajSoftware.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RajSoftware.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest ASP.NET &amp; ASP.NET MVC Links.
        /// </summary>
        public static string AspNetLinksHeader {
            get {
                return ResourceManager.GetString("AspNetLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASP.NET MVC Links.
        /// </summary>
        public static string AspNetMvcLinksHeader {
            get {
                return ResourceManager.GetString("AspNetMvcLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links to favourite Blogs.
        /// </summary>
        public static string BlogHeader {
            get {
                return ResourceManager.GetString("BlogHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rajitha_kba@yahoo.com.au.
        /// </summary>
        public static string EmailValue {
            get {
                return ResourceManager.GetString("EmailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently Reading.
        /// </summary>
        public static string HeaderBooksReading {
            get {
                return ResourceManager.GetString("HeaderBooksReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events attended.
        /// </summary>
        public static string HeaderEvents {
            get {
                return ResourceManager.GetString("HeaderEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string lblEmail {
            get {
                return ResourceManager.GetString("lblEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Blog.
        /// </summary>
        public static string MyBlogNameHeader {
            get {
                return ResourceManager.GetString("MyBlogNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interesting News &amp; Events.
        /// </summary>
        public static string NewHeader {
            get {
                return ResourceManager.GetString("NewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raj Software.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patterns &amp; Practices.
        /// </summary>
        public static string PatternNpracticesLinksHeader {
            get {
                return ResourceManager.GetString("PatternNpracticesLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups.
        /// </summary>
        public static string UserGroupsTitle {
            get {
                return ResourceManager.GetString("UserGroupsTitle", resourceCulture);
            }
        }
    }
}
